name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Set up JDK 10
        uses: actions/setup-java@v1
        with:
          java-version: 10
      - name: Build with Maven
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: mvn -DrepoToken=$COVERALLS_TOKEN clean package cobertura:cobertura coveralls:report
